---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`matomo.local`)
    kind: Rule
    services:
    - name: matomo-service
      port: 80
  - match: Host(`frontend.local`)
    kind: Rule
    services:
    - name: nginx-service
      port: 80
  - match: Host(`frontendbase.local`)
    kind: Rule
    services:
    - name: nginx-base-service
      port: 80  
  - match: Host(`kibana.local`)
    kind: Rule
    services:
    - name: elk
      port: 5601  
  - match: Host(`backend.local`)
    kind: Rule
    services:
    - name: nginx-service-backend
      port: 80   